# GitHub Actions workflow to run API tests on pull requests
# against the main branch
name: API Tests

# Trigger on pull requests against main branch
on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run API Tests
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Latest LTS version
          cache: 'npm'          # Cache npm dependencies

      # Set up environment using existing script
      - name: Set up test environment
        run: npm run pretest:env

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run tests
      - name: Run tests
        run: npm run test:ci

      # Upload test results as artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()  # Run even if previous steps fail
        with:
          name: test-results
          path: junit.xml

      # Upload coverage report as artifacts
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        if: always()  # Run even if previous steps fail
        with:
          name: coverage-report
          path: coverage/

      # Add test results as PR comment
      - name: Comment PR with test results summary
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()  # Run even if previous steps fail
        with:
          files: junit.xml

